### ISSUE TITLE
Deleting Sensor Does not Remove it from the Logging Menu

### ISSUE THREAD

**Issue by MrMeik** [Jaren-Taylor/Smart-City-Dashboard#44]
If I use the tile sensor inspector and click on a tile with a sensor. If I delete that sensor, the corresponding one in the logging menu does not get deleted.

**Comment by Xerner** [comment]
Replicated case above for CameraSensors and TrafficLightSensors and both remove themselves from the log menu as intended ¯\_(ツ)_/¯
