### ISSUE TITLE
Cursor Disabled During Normal Gameplay

### ISSUE THREAD

**Issue by MrMeik** [Jaren-Taylor/Smart-City-Dashboard#45]
Not sure what I did to cause it but the CursorEnabled bool was flipped negative at a point where it should not have been. I was flipping between states as normal. I noticed the cursor was not showing up around the time I went into the debug menu and hit either 1 / 2 and tried clicking on a car.

Things I know I did do:
	-Place roads
	-Place houses
	-Delete houses
	
Things I tried but was unable to do:
	-Go into first person via debug 1 button
	-Place traffic light with debug 2 button
	-Place camera sensor with button
	
I opened the debugger and observed that the CursorEnabled was set false even though my cursor was over the middle of the screen not over any UI

**Comment by Xerner** [comment]
Fixed by adding proper Action listeners in Menu.cs
